version: '3.9'

services:
  # Serviço do Traefik
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # Porta HTTP
      - "8080:8080"   # Dashboard do Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Necessário para integração com o Docker

  # Serviço do Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.local`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  # Serviço do Apache2
  apache:
    image: httpd:latest
    container_name: apache2
    labels:
      - "traefik.http.routers.apache.rule=Host(`apache.localhost`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
